---
- name: Engine VM configuration tasks
  block:
  - include_tasks: pg_scl.yml
  - name: Update target VM details at DB level
    command: "{{ scl_pg_prefix }} psql -d engine -c \"UPDATE vm_static SET {{ item.field }}={{ item.value }} WHERE vm_guid='{{ hostvars['localhost']['he_vm_details']['vm']['id'] }}'\""
    environment: "{{ he_cmd_lang }}"
    become: true
    become_user: postgres
    become_method: sudo
    changed_when: True
    register: db_vm_update
    with_items:
      - { field: 'origin', value: 6 }
  - debug: var=db_vm_update
  - name: Insert Hosted Engine configuration disk uuid into Engine database
    command: "{{ scl_pg_prefix }} psql -d engine -c \"UPDATE vdc_options SET option_value='{{ hostvars['localhost']['he_conf_disk_details']['disk']['id'] }}' WHERE option_name='HostedEngineConfigurationImageGuid' AND version='general'\""
    environment: "{{ he_cmd_lang }}"
    become: true
    become_user: postgres
    become_method: sudo
    changed_when: True
    register: db_conf_update
  - debug: var=db_conf_update
  - name: Fetch host SPM_ID
    command: "{{ scl_pg_prefix }} psql -t -d engine -c \"SELECT vds_spm_id FROM vds WHERE vds_name='{{ HOST_NAME }}'\""
    environment: "{{ he_cmd_lang }}"
    become: true
    become_user: postgres
    become_method: sudo
    changed_when: True
    register: host_spm_id_out
  - name: Parse host SPM_ID
    set_fact: host_spm_id="{{ host_spm_id_out.stdout_lines|first|trim }}"
  - debug: var=host_spm_id
  - name: Disable IPv6
    lineinfile:
      path: /etc/sysctl.conf
      line: 'net.ipv6.conf.all.disable_ipv6=1'
  - name: Reload sysctl
    command: sysctl -p
    environment: "{{ he_cmd_lang }}"
    changed_when: True